# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trust_region_cpp <- function(objfun, parinit, rinit, rmax, iterlim, minimize, tol, eta, lower, upper) {
    .Call(`_vntrs_trust_region_cpp`, objfun, parinit, rinit, rmax, iterlim, minimize, tol, eta, lower, upper)
}

vntrs_cpp <- function(f, npar, minimize, init_runs, init_min, init_max, init_iterlim, neighborhoods, neighbors, beta, iterlim, tolerance, inferior_tolerance, has_time_limit, time_limit, cores, lower, upper, quiet, collect_all_optima) {
    .Call(`_vntrs_vntrs_cpp`, f, npar, minimize, init_runs, init_min, init_max, init_iterlim, neighborhoods, neighbors, beta, iterlim, tolerance, inferior_tolerance, has_time_limit, time_limit, cores, lower, upper, quiet, collect_all_optima)
}

